version: 2
updates:
  - package-ecosystem: gradle
    directory: "/product-management-api"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/product-management-web"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/product-management-api"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/product-management-web"
    schedule:
      interval: weekly