apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-web

spec:
  replicas: 2

  selector:
    matchLabels:
      app: product-web

  template:
    metadata:
      labels:
        app: product-web

    spec:
      containers:
      - name: product-web
        image: ghcr.io/apchavez/product-web:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
